version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 961341539878.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image for frontend...
      - docker build -t collabspace-prod ./Frontend/Team-Collab-Tool
      - echo Tagging the Docker image...
      - docker tag collabspace-prod:latest 961341539878.dkr.ecr.ap-south-1.amazonaws.com/collabspace-prod:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 961341539878.dkr.ecr.ap-south-1.amazonaws.com/collabspace-prod:latest
artifacts:
  files:
    - "**/*"
